### ISSUE TITLE
Use PSR-2 standards

### ISSUE THREAD

**Issue by curtisgibby** [Xety/Cake3-Sluggable#2]
CakePHP recommends using PSR-2, but you're using tabs instead of spaces, putting method opening braces on the same line, etc.

**Comment by Xety** [comment]
Hey,

Yes, i know. As you can see, the latest commit in this repo was 1 year ago, and i didn't got the time to update my plugins yet.

Feel free to do a PR. :)

**Comment by Xety** [comment]
Fixed in #3
